### ISSUE TITLE
Add currency symbol

### ISSUE THREAD

**Issue by ajmas** [andyburke/countrydata#1]
It would be useful to add the currency symbol and whether it is prefixed or suffixed.

For example:

```

        "iso3166": {
            "alpha2": "US",
            "alpha3": "USA",
            "independent": true,
            "name": "United States",
            "numeric": 840,
            "currency": {
                "name": "US Dollar",
                "code": "USD",
                "numeric": 840,
                "minor_unit": 2,
                "symbol": "$",
                "prefixSymbol": true
            }
        },
```

**Comment by andyburke** [comment]
I'll gladly accept a PR with this.

**Comment by ajmas** [comment]
Just dropping this here for reference, to start with: https://www.currencyremitapp.com/world-currency-symbols/

[currency-with-symbols.xlsx](https://github.com/andyburke/countrydata/files/5113370/currency-with-symbols.xlsx)

**Comment by ajmas** [comment]
I have made a PR for the symbol, but for now I haven't been to get anything for the currency symbol position.

Reading this, maybe something can be garnered from Java, but I haven't done that work:

https://getaround.tech/multi-currency-java/

or possibly: 

http://cldr.unicode.org/#TOC-How-to-Use-

Though this will probably be an issue for another ticket
