### ISSUE TITLE
Increase version and make new NPM release

### ISSUE THREAD

**Issue by ajmas** [andyburke/countrydata#3]
Following changes and merge of issue #1 we should increase the version in package.json and make a new release.

**Comment by andyburke** [comment]
I've bumped the version and released at 3.0.0.

Please take a look at the new API where it returns an array of currency objects for a country. (Some countries use multiple currencies.) All currencies should now have a symbol, as well.

If things look good to you, go ahead and close this issue. If you spot anything related to the release, please update this issue.

**Comment by andyburke** [comment]
Thanks for the initial PR for the currency symbols. It's what I based most of this new work off of, while filling in some gaps.
